### ISSUE TITLE
latest npm version doesn't seem to have any dist folder

### ISSUE THREAD

**Issue by bkniffler** [intacct/intacct-sdk-js#102]
<img width="353" alt="Bildschirmfoto 2022-09-18 um 17 00 57" src="https://user-images.githubusercontent.com/4349324/190913713-2be4dc6c-055e-46ef-ae21-39bdcdf12058.png">

Latest version has no dist.

**Comment by dylan-holt-sage** [comment]
@bkniffler, we recently created GitHub actions for this repo for publishing and made an error on this item. We have a fix incoming shortly! Thanks for letting us know.

**Comment by dylan-holt-sage** [comment]
@bkniffler, this has been resolved in 2.2.1 :)
