### ISSUE TITLE
ReadByName does not work properly

### ISSUE THREAD

**Issue by zSkalin** [Intacct/intacct-sdk-js#24]
When running IA.Functions.Common.ReadByName() on object name 'CONTACT' and providing the 'CONTACTNAME' I get zero results.

When running IA.Functions.Common.ReadByQuery() on object name 'CONTACT' and providing the following query "CONTACTNAME = 'ExampleContact'", I get the record I was looking for.

What is the difference between these two query types?

````javascript
const query = new IA.Functions.Common.ReadByName();
    query.objectName = 'CONTACT';
    query.names = ['ExampleContact'];
    query.fields = ['*'];
````

````javascript
const query = new IA.Functions.Common.ReadByQuery();
    query.objectName = 'CONTACT';
    query.fields = ['*'];
    query.query = new IA.Functions.Common.Query.QueryString("CONTACTNAME = 'ExampleContact'");
````

**Comment by jimmymcpeter** [comment]
Just a random guess, but it might be like your other issue with an entity-private record.

**Comment by jimmymcpeter** [comment]
Best thing you can do is to enable debug level logging so you can get the full XML request being sent in.  Check out the little snippet here - https://github.com/Intacct/intacct-sdk-node-js-examples/blob/master/bootstrap.js#L23-L43
