### ISSUE TITLE
ContactUpdate does not work properly

### ISSUE THREAD

**Issue by zSkalin** [Intacct/intacct-sdk-js#25]
When using ContactUpdate, it will randomly tell me that the contact does not exist

'Cannot update non-existing CONTACT with CONTACTNAME=ExampleContactName'

I know this contact exists because I check if it exists using IA.Functions.Common.ReadByQuery() before I attempt to update it.

Code Example

````javascript
const query = new IA.Functions.Company.ContactUpdate();
      
      query.contactName = contact.CONTACTNAME;
      query.printAs = contact.PRINTAS;
      query.companyName = contact.COMPANYNAME;
      query.taxable = contact.TAXABLE;
      query.taxId = contact.TAXID;
      query.contactTaxGroupName = contact.TAXGROUP;
      query.prefix = contact.PREFIX;
      query.firstName = contact.FIRSTNAME;
      query.lastName = contact.LASTNAME;
      query.middleName = contact.INITIAL;
      query.primaryPhoneNo = contact.PHONE1;
      query.secondaryPhoneNo = contact.PHONE2;
      query.cellularPhoneNo = contact.CELLPHONE;
      query.pagerNo = contact.PAGER;
      query.faxNo = contact.FAX;
      query.primaryEmailAddress = contact.EMAIL1;
      query.secondaryEmailAddress = contact.EMAIL2;
      query.primaryUrl = contact.URL1;
      query.secondaryUrl = contact.URL2;
      query.active = (contact.STATUS === 'active') || false;

      query.addressLine1 = contact['MAILADDRESS.ADDRESS1'];
      query.addressLine2 = contact['MAILADDRESS.ADDRESS2'];
      query.city = contact['MAILADDRESS.CITY'];
      query.stateProvince = contact['MAILADDRESS.STATE'];
      query.zipPostalCode = contact['MAILADDRESS.ZIP'];
      query.country = contact['MAILADDRESS.COUNTRY'];
      query.isoCountryCode = contact['MAILADDRESS.COUNTRYCODE'];

      try {
        const response = await this.client.execute(query);
        resolve(response.getResult());
      } catch (err) {
        reject(err);
      }
````

**Comment by jimmymcpeter** [comment]
Are you running the readByQuery at the top level in a multi-entity shared company, and the contact was created privately in an entity?  Look at the `MEGAENTITYID` field in the response.  In order to do an update/delete on an entity-private record, you must be in the authentication context of the entity.

**Comment by zSkalin** [comment]
Hi Jimmy,

I double checked the EntityID I set in my clientConfig and it is set to the right EntityID,

I am using the exact same OnlineClient object for both calls

Function example to check if the contact exists
````javascript
const query = new IA.Functions.Common.ReadByQuery();
    query.objectName = 'CONTACT';
    query.fields = ['*'];
    query.query = new IA.Functions.Common.Query.QueryString("CONTACTNAME = 'ExampleContact'");

    try {
      const response = await this.client.execute(query);
      return response.getResult();
    } catch (err) {
      console.log(err);
    }
````

With the result from the previous function, if it returned a contact I run the update else it creates a new contact.

**Comment by jimmymcpeter** [comment]
Without access to your environment I'm unsure honestly.  If you add a debug level logger to your client config, this will log the XML requests and responses being sent.  I can take a look at them but the best route might be to add them to a case with Sage Intacct Customer Support since they can access your company.

**Comment by zSkalin** [comment]
I have submitted a support ticket, they are looking into it as well,?

The updateContact function looks like its double escaping,

In the error response i see 

"Cannot update non-existing CONTACT with CONTACTNAME=Example &amp;amp; Contact"
