### ISSUE TITLE
Query is not working properly

### ISSUE THREAD

**Issue by federico-solveit** [Intacct/intacct-sdk-js#28]
Hi.
I am trying to pull REVRECSCHEDULEENTRY records using ReadByQuery.
When I the query parameter blank, it works well with all results. (total: 8863)
But If I set the query to "POSTED = 'Posted'", it doesn't pull any data. (total: 0)
Thanks.

**Comment by jimmymcpeter** [comment]
The query value is not the label.  It's likely `X` or `P`
