### ISSUE TITLE
Support for PlatformServices API 

### ISSUE THREAD

**Issue by dipeenverma1609** [Intacct/intacct-sdk-js#29]
Do we support PlatformService API ?
link: https://developer.intacct.com/api/platform-services/

**Comment by intacctcoleenho** [comment]
Could you be more specific?  Is there something in particular you are looking for the Platform Services to support through our API?

**Comment by intacctcoleenho** [comment]
Closing issue due to no response. Assuming your issue has been resolved.
Thanks!
