### ISSUE TITLE
How do I read GL balances using this SDK?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Intacct/intacct-sdk-js#38]
Since there is no tutorial, I was wondering how it was possible to read "account balance by dimension" from https://developer.intacct.com/api/general-ledger/account-balances/ .

Is this currently supported at all?
What would be the right way to approach this?

**Comment by intacctcoleenho** [comment]
Currently the SDK doesn't support this. This request would be an enhancement.

**Comment by intacctcoleenho** [comment]
I suggest you check out DdsJobCreate for containing all information together for making this request (and ApAdjustmentCreate to see how to write the date in the split format for <startdate> and <enddate> elements).  DdsJobCreate will show you an approach for how to implement this overall.  Feel free to submit a pull request if you do implement this and we will review it for adding to the SDK.  Thanks!

**Comment by mcarson28** [comment]
@intacctcoleenho is it possible to use one of the common functions (IA.Functions.Common) to request the account balance data?

**Comment by mcarson28** [comment]
@intacctcoleenho Unless I'm underthinking this, I don't think it would be too difficult to add this functionality.  I'd be interested in creating a PR for this.  I assume it would mainly involve creating a new class in Functions/GeneralLedger? Something like AccountBalanceList?  Let me know if this would be something you'd merge and if there is any documentation for what is needed to merge.
