### ISSUE TITLE
Fix Typedoc links to the source code

### ISSUE THREAD

**Issue by jimmymcpeter** [Intacct/intacct-sdk-js#4]
It looks like it's linking to older blobs of the code and not the version it compiled against.  We need to figure out where it is pulling/using this from.

**Comment by intacctcoleenho** [comment]
Do you have an example of this?

**Comment by jimmymcpeter** [comment]
Hover over the Defined in links and notice the `blob/...` link goes to an older version

![image](https://user-images.githubusercontent.com/11491046/41935842-2e61b864-7959-11e8-97e2-042235243219.png)

**Comment by jimmymcpeter** [comment]
Looks like typedoc has a command line argument to accomplish this -- http://typedoc.org/api/

`--gitRevision <revision|branch>`
Use specified revision or branch instead of the last revision for linking to GitHub source files.
