### ISSUE TITLE
When will online payments be available in ArPaymentCreate?

### ISSUE THREAD

**Issue by dan2kx** [intacct/intacct-sdk-js#61]
Im using the SDK to allow our customers to pay invoices and noticed the TODO to add online payment which is documented in the API (ONLINECARDPAYMENT). I am writing a custom function to handle this for now, but I just wondered when this will be available within the SDK?

**Comment by dylan-holt-sage** [comment]
@dan2kx , sorry for the late response. Took a look at what you're referring and I can have this done soon. It'll be in upcoming JS SDK release.
