### ISSUE TITLE
Ability to Pull PDF from Order Entry

### ISSUE THREAD

**Issue by haislip** [Intacct/intacct-sdk-js#73]
https://developer.intacct.com/api/order-entry/order-entry-transactions/#get-order-entry-transaction-pdf-data

**Comment by haislip** [comment]
https://github.com/Intacct/intacct-sdk-js/pull/72

**Comment by dylan-holt-sage** [comment]
Closing this issue as the raised PR has been reviewed and merged :) Thanks again @haislip

**Comment by haislip** [comment]
@dylan-holt-sage Thank you!
