### ISSUE TITLE
Adding Missing fields

### ISSUE THREAD

**Issue by mcarson28** [intacct/intacct-sdk-js#76]
Is it possible to add missing fields that are in the native api but not the nodejs SDK?  For example offsetGLAccount for Vendors is available in the API but not on the SDK.

**Comment by tehnorm** [comment]
It looks like for Creating a GL entry `COSTTYPEID` is missing as well from the SDK.

**Comment by dylan-holt-sage** [comment]
@mcarson28 / @tehnorm, we can add missing fields :) please let us know of more fields that are missing which your respective teams would like to use so we can add them. Also, thanks for letting us know!

**Comment by mcarson28** [comment]
The missing field I was referring to was the following from the Vendor API Docs

APACCOUNT | Optional | string | Default expense GL account number

**Comment by tehnorm** [comment]
@dylan-holt-sage it might make sense to audit the API's vs what is in this lib? I needed GL entry `COSTTYPEID` but there seem to be many others to be added.

**Comment by mcarson28** [comment]
@dylan-holt-sage also, I don't see description on order entry.  Is that something that could be added?

**Comment by dylan-holt-sage** [comment]
@tehnorm / @mcarson28, I'll see what I can do from the audit perspective. May take some time since .NET SDK is next priority. I'll add everything that's explicitly been mentioned for the upcoming release and plan other items for when there is time.

**Comment by dylan-holt-sage** [comment]
@mcarson28 , which description on order entry are you referring to? The PCB related descriptions? Subtotals has the descriptions there.

**Comment by johnsonj081** [comment]
Hi there, 

I've got two queries I was hoping you could help me with.

1. I need to create transactions that multiple lines, with different tax solutions on each, however, I can't seem to find the related tax fields that will enable me to do this. Is there a way of me creating them?

2. The other query I have is in relation to creating advances (payments on account). I'm also unable to find documentation on how to go about this through the NodeJS SDK. Is this something that already exists or is it possible for to create this?

**Comment by johnsonj081** [comment]
Hi Dylan,

I appreciate your response. I've logged the requirement for advances as an
issue now.

As for my first issue raised, I'm going to run some tests just to be 100%
sure on which transactions will require tax information, and which tax data
points will actually be required. Once I've completed this I'll raise a
separate issue in GitHub.

Kind regards,
Jamie

**Comment by johnsonj081** [comment]
Hi Dylan,

I can confirm that the data points we need are for invoices and adjustments
on both the AP and AR side. For each line within each of these
transactions, we need to be able to add Tax Solutions, Tax Detail
ID's and Tax Amounts.

Just for some context, I am an employee of ION. We're a partner with Sage
and this piece of work is essential to completing an implementation that is
currently in progress.

Kind regards,
Jamie
