### ISSUE TITLE
AR Invoice fulfillmentStatus set incorrectly

### ISSUE THREAD

**Issue by lprichar** [intacct/intacct-sdk-js#77]
If you try to create an invoice with a `fulfillmentStatus` like:

```
const command = new OrderEntryTransactionLineCreate();
command.fulfillmentStatus = 'Undelivered'
```

Then you get back: `XL03000003 XML Parse schema error: Error 1843: Element 'fulfillmentstatus': Character content other than whitespace is not allowed because the content type is 'element-only'`.  That happens because `fulfillmentstatus` is being treated as a string rather than an element with subelements.  See also: https://developer.intacct.com/api/order-entry/order-entry-transactions/#create-order-entry-transaction-legacy.

**Comment by dylan-holt-sage** [comment]
PR related to this issue has been reviewed and merged to upcoming JS release. Closing this issue.
