### ISSUE TITLE
Bank Feeds

### ISSUE THREAD

**Issue by bkniffler** [intacct/intacct-sdk-js#79]
Is there a reason that there's no endpoints presented at https://developer.intacct.com/api/cash-management/bank-feeds/ reflected in the sdk?

**Comment by dylan-holt-sage** [comment]
@bkniffler, not sure why it was not in the SDK prior to now, but we can definitely add this in the next release (TBD).

**Comment by dylan-holt-sage** [comment]
changes for this item will be coming in the next release :)
