### ISSUE TITLE
How can I update an APPayment?

### ISSUE THREAD

**Issue by bogdanbrnd** [intacct/intacct-sdk-js#81]
Hi,
I looked on the js-sdk and I didn't find any way to update an APPayment.
How can I update an APPayment?
Thanks 
Bogdan

**Comment by dylan-holt-sage** [comment]
@bogdanbrnd , there currently isn't a way through SDK to do so, but I shall work on implementing this for upcoming JS SDK release. Thank you for your question.

**Comment by dylan-holt-sage** [comment]
Has been implemented and will be in upcoming JS SDK release. Closing this issue.
