### ISSUE TITLE
Some fields in APBILL and APBILLITEM cannot be queried

### ISSUE THREAD

**Issue by justin-ch** [intacct/intacct-sdk-js#83]
Hello,

I'm seeing an error when querying some fields in these two objects using `IA.Functions.Common.NewQuery.Query`.

`ResultException [Error]: Result status: failure for Control ID: 65d824c7-68c1-4a9c-9cea-cc4007c76ac6 - XL03000006 The following fields cannot be queried: [
        apbill: [PAYTOCONTACTNAME, RETURNTOCONTACTNAME] ] [Support ID: LYF3ZEB034%7EYeogyP0F2YJ-hwZWD-iCgQAAABU]
`

These are the fields that I've run into issues with:

APBILL
- PAYTOCONTACTNAME
- RETURNTOCONTACTNAME

APBILLITEM
- GLACCOUNTNO

I'm using the version 2.1.1 of the `@intacct/intacct-sdk`

**Comment by ryan-holderfield-sage** [comment]
Hi @justin-ch, please be sure to build/validate your fields for the new query function by using the lookup function:

[Developers Site for query](https://developer.intacct.com/web-services/queries/)

[Lookup function](https://intacct.github.io/intacct-sdk-js/classes/intacct_sdk_functions_platformservices.lookup.html)

**Comment by dylan-holt-sage** [comment]
@justin-ch, did the above comment resolve your issue?

**Comment by dylan-holt-sage** [comment]
Closing this issue.... if it is persisting, please reopen and we will revisit.
