### ISSUE TITLE
BL03002128: Error while creating bill record

### ISSUE THREAD

**Issue by yungtilly** [intacct/intacct-sdk-js#86]
Hello,

My team has encountered an error while attempting to create a new bill using the Javascript SDK.

For a little bit of background, we built a microservice to allow various databases to interact with the Intacct system. 
The following JSON object gets mapped to the appropriate fields in the SDK's BillCreate object:

`[
  {
    "VENDORID": "20200",
    "WHENCREATED": "2022-02-21",
    "WHENDUE": "2022-03-10",
    "APBILLITEMS": [
      {
        "ACCOUNTNO": "60410",
        "TRX_AMOUNT": "9.45",
        "LOCATIONID": "100",
        "DEPARTMENTID": "100"
      }
    ]
  }
]
`

However, we're pretty consistently getting the following response:

`{
    "response": {
        "errors": [
            "BL03002128 Enter a Bill number, and try again. [Support ID: BHF%401EB034%7EYhVWlP0o213-8KQW5T4tIQAAAB4]",
            "BL01001973 Currently, we can't create the transaction Check the transaction for errors or inconsistencies, then try again."
        ]
    },
    "status": 400,
    "message": "Result status: failure for Control ID: 5de1e778-6882-477c-aa3e-0e19a706bba5 - BL03002128 Enter a Bill number, and try again. [Support ID: BHF%401EB034%7EYhVWlP0o213-8KQW5T4tIQAAAB4] - BL01001973 Currently, we can't create the transaction Check the transaction for errors or inconsistencies, then try again."
}`

I'm having a little bit of trouble interpreting this error message because I'm not aware of a way to include a bill number in our create call based on the SDK docs (and wouldn't the bill number be generated on creation anyway?).

Anything you can do to help me get to the bottom of this error would be greatly appreciated by my team and me!

**Comment by rholderfield** [comment]
Hi,

Please see the following document:
https://developer.intacct.com/api/accounts-payable/bills/#create-bill-legacy

BillCreate:
https://github.com/Intacct/intacct-sdk-js/blob/bdadac479a3ac6c8b2a34e5429b1ddf3afa740f1/src/Functions/AccountsPayable/BillCreate.ts#L54

The bill number for AP transactions are going to be company configuration specific. Either not required, dynamically set by the system, or manually.

**Comment by dylan-holt-sage** [comment]
Closing this issue.... if it is persisting, please reopen and we will revisit.
