### ISSUE TITLE
GH Pages branch is outdated

### ISSUE THREAD

**Issue by de-zakauff** [intacct/intacct-sdk-js#97]
Additionally, the documentation included in the pages isn't all that helpful due to lack of actual documentation / comments. It would be great to see the pages updated to at least be up to date with the current SDK version.

**Comment by dylan-holt-sage** [comment]
Hey @de-zakauff, that will be resolved soon.

**Comment by dylan-holt-sage** [comment]
@de-zakauff, should be updated to the current SDK now.
